#!/bin/bash -l
#
# CP2K on Piz Daint
#SBATCH -A s957
#SBATCH --job-name=ft-time
#SBATCH --time=00:10:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --partition=normal
#SBATCH --constraint=gpu


#========================================
# load modules and run simulation
module load daint-gpu

export OMP_NUM_THREADS=1

python ../ft-time.py density-real 1000 &> tmplog1 &
python ../ft-time.py density-imag 1000 &> tmplog2 &
wait

rm tmplog?
